# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{capistrano-git}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ryan Moran}]
  s.date = %q{2011-11-21}
  s.description = %q{Capistrano recipe for deploying from git}
  s.email = %q{ryan.moran@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "capistrano-git.gemspec",
    "lib/capistrano/git.rb",
    "lib/capistrano/git/overrides.rb",
    "lib/capistrano/git/strategy.rb",
    "test/helper.rb",
    "test/test_capistrano-git.rb"
  ]
  s.homepage = %q{http://github.com/ryanmoran/capistrano-git}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Capistrano recipe for deploying from git}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano_colors>, ["= 0.5.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<capistrano_colors>, ["= 0.5.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<capistrano_colors>, ["= 0.5.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

